config/routes.rb
        resources :listings, only: %i[index show create update]
        get "/listings/category/:category", to: "listings#index", as: :listings_category
        get "/analytics/totals", to: "analytics#totals"
        get "/analytics/historical", to: "analytics#historical"
        get "/analytics/past_day", to: "analytics#past_day"
        get "/analytics/referrers", to: "analytics#referrers"

        resources :health_checks, only: [] do
          collection do
            get :app
            get :database
            get :cache
          end
        end

        resources :profile_images, only: %i[show], param: :username
        resources :organizations, only: [:show], param: :username do
          resources :users, only: [:index], to: "organizations#users"
          resources :listings, only: [:index], to: "organizations#listings"
          resources :articles, only: [:index], to: "organizations#articles"
        end

        namespace :admin do
          resource :config, only: %i[show update], defaults: { format: :json }
        end
      end
    end

    namespace :notifications do
      resources :counts, only: [:index]
      resources :reads, only: [:create]
    end

    namespace :incoming_webhooks do
      get "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#index", as: :mailchimp_unsubscribe_check
      post "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#create", as: :mailchimp_unsubscribe
    end

    resources :messages, only: [:create]
    resources :chat_channels, only: %i[index show create update]
    resources :chat_channel_memberships, only: %i[index create edit update destroy]
    resources :articles, only: %i[update create destroy] do
      patch "/admin_unpublish", to: "articles#admin_unpublish"
    end
    resources :article_mutes, only: %i[update]
    resources :comments, only: %i[create update destroy] do
      patch "/hide", to: "comments#hide"
      patch "/unhide", to: "comments#unhide"
      patch "/admin_delete", to: "comments#admin_delete"
      collection do
        post "/moderator_create", to: "comments#moderator_create"
      end
    end
    resources :comment_mutes, only: %i[update]
    resources :users, only: %i[index], defaults: { format: :json } do # internal API
      collection do
        resources :devices, only: %i[create destroy]
      end
    end
    resources :users, only: %i[update]
    resources :reactions, only: %i[index create]
    resources :response_templates, only: %i[index create edit update destroy]
    resources :feedback_messages, only: %i[index create]
    resources :organizations, only: %i[update create destroy]
    resources :followed_articles, only: [:index]
    resources :follows, only: %i[show create] do
      collection do
        get "/bulk_show", to: "follows#bulk_show"
        patch "/bulk_update", to: "follows#bulk_update"
      end
    end
    resources :image_uploads, only: [:create]
    resources :notifications, only: [:index]
    resources :tags, only: [:index] do
      collection do
        get "/onboarding", to: "tags#onboarding"
      end
    end
    resources :stripe_active_cards, only: %i[create update destroy]
    resources :github_repos, only: %i[index] do
      collection do
        post "/update_or_create", to: "github_repos#update_or_create"
      end
    end
    resources :events, only: %i[index show]
    resources :videos, only: %i[index create new]
    resources :video_states, only: [:create]
    resources :twilio_tokens, only: [:show]
    resources :html_variant_trials, only: [:create]
    resources :html_variant_successes, only: [:create]
    resources :tag_adjustments, only: %i[create destroy]
    resources :rating_votes, only: [:create]
    resources :page_views, only: %i[create update]
    resources :listings, only: %i[index new create edit update destroy dashboard]
    resources :credits, only: %i[index new create] do
      get "purchase", on: :collection, to: "credits#new"
    end
    resources :reading_list_items, only: [:update]
    resources :poll_votes, only: %i[show create]
    resources :poll_skips, only: [:create]
    resources :profile_pins, only: %i[create update]
    resources :display_ad_events, only: [:create]
    resources :badges, only: [:index]
    resources :user_blocks, param: :blocked_id, only: %i[show create destroy]
    resources :podcasts, only: %i[new create]
    resources :article_approvals, only: %i[create]
    resources :video_chats, only: %i[show]
    resources :sidebars, only: %i[show]
    resources :user_subscriptions, only: %i[create] do
      collection do
        get "/subscribed", action: "subscribed"
      end
    end
    namespace :followings, defaults: { format: :json } do
      get :users
      get :tags
      get :organizations
      get :podcasts
    end

    resource :onboarding, only: :show
    resources :profiles, only: %i[update]
    resources :profile_field_groups, only: %i[index], defaults: { format: :json }

    resources :liquid_tags, only: %i[index], defaults: { format: :json }

    get "/verify_email_ownership", to: "email_authorizations#verify", as: :verify_email_authorizations
    get "/search/tags", to: "search#tags"
    get "/search/chat_channels", to: "search#chat_channels"
    get "/search/listings", to: "search#listings"
    get "/search/usernames", to: "search#usernames"
    get "/search/feed_content", to: "search#feed_content"
    get "/search/reactions", to: "search#reactions"
    get "/chat_channel_memberships/find_by_chat_channel_id", to: "chat_channel_memberships#find_by_chat_channel_id"
    get "/listings/dashboard", to: "listings#dashboard"
    get "/listings/:category", to: "listings#index", as: :listing_category
    get "/listings/:category/:slug", to: "listings#index", as: :listing_slug
    get "/listings/:category/:slug/:view", to: "listings#index",
                                           constraints: { view: /moderate/ }
    get "/listings/:category/:slug/delete_confirm", to: "listings#delete_confirm"
    delete "/listings/:category/:slug", to: "listings#destroy"
    get "/notifications/:filter", to: "notifications#index"
    get "/notifications/:filter/:org_id", to: "notifications#index"
    get "/notification_subscriptions/:notifiable_type/:notifiable_id", to: "notification_subscriptions#show"
    post "/notification_subscriptions/:notifiable_type/:notifiable_id", to: "notification_subscriptions#upsert"
    patch "/onboarding_update", to: "users#onboarding_update"
    patch "/onboarding_checkbox_update", to: "users#onboarding_checkbox_update"
    get "email_subscriptions/unsubscribe"
    post "/chat_channels/:id/moderate", to: "chat_channels#moderate"
    post "/chat_channels/:id/open", to: "chat_channels#open"
    get "/connect", to: "chat_channels#index"
    get "/connect/:slug", to: "chat_channels#index"
    get "/chat_channels/:id/channel_info", to: "chat_channels#channel_info", as: :chat_channel_info
    post "/chat_channels/create_chat", to: "chat_channels#create_chat"
    post "/chat_channels/block_chat", to: "chat_channels#block_chat"
    post "/chat_channel_memberships/remove_membership", to: "chat_channel_memberships#remove_membership"
    post "/chat_channel_memberships/add_membership", to: "chat_channel_memberships#add_membership"
    post "/join_chat_channel", to: "chat_channel_memberships#join_channel"
    delete "/messages/:id", to: "messages#destroy"
    patch "/messages/:id", to: "messages#update"
    get "/internal", to: redirect("/admin")
    get "/internal/:path", to: redirect("/admin/%{path}")

    post "/pusher/auth", to: "pusher#auth"

    patch "/chat_channels/update_channel/:id", to: "chat_channels#update_channel"
    post "/create_channel", to: "chat_channels#create_channel"

    get "/chat_channel_memberships/chat_channel_info/:id", to: "chat_channel_memberships#chat_channel_info"
    post "/chat_channel_memberships/create_membership_request", to: "chat_channel_memberships#create_membership_request"
    patch "/chat_channel_memberships/leave_membership/:id", to: "chat_channel_memberships#leave_membership"
    patch "/chat_channel_memberships/update_membership/:id", to: "chat_channel_memberships#update_membership"
    get "/channel_request_info/", to: "chat_channel_memberships#request_details"
    patch "/chat_channel_memberships/update_membership_role/:id", to: "chat_channel_memberships#update_membership_role"
    get "/join_channel_invitation/:channel_slug", to: "chat_channel_memberships#join_channel_invitation"
    post "/joining_invitation_response", to: "chat_channel_memberships#joining_invitation_response"

    get "/social_previews/article/:id", to: "social_previews#article", as: :article_social_preview
    get "/social_previews/user/:id", to: "social_previews#user", as: :user_social_preview
    get "/social_previews/organization/:id", to: "social_previews#organization", as: :organization_social_preview
    get "/social_previews/tag/:id", to: "social_previews#tag", as: :tag_social_preview
    get "/social_previews/listing/:id", to: "social_previews#listing", as: :listing_social_preview
    get "/social_previews/comment/:id", to: "social_previews#comment", as: :comment_social_preview

    get "/async_info/base_data", controller: "async_info#base_data", defaults: { format: :json }
    get "/async_info/shell_version", controller: "async_info#shell_version", defaults: { format: :json }

    post "users/join_org", to: "users#join_org"
    post "users/leave_org/:organization_id", to: "users#leave_org", as: :users_leave_org
    post "users/add_org_admin", to: "users#add_org_admin"
    post "users/remove_org_admin", to: "users#remove_org_admin"
    post "users/remove_from_org", to: "users#remove_from_org"
    delete "users/remove_identity", to: "users#remove_identity"
    post "users/request_destroy", to: "users#request_destroy", as: :user_request_destroy
    get "users/confirm_destroy/:token", to: "users#confirm_destroy", as: :user_confirm_destroy

app/models/ahoy/event.rb
module Ahoy
  class Event < ApplicationRecord
    include Ahoy::QueryMethods

    self.table_name = "ahoy_events"

    belongs_to :visit
    belongs_to :user, optional: true

    scope :overview_link_clicks, -> { where(name: "Admin Overview Link Clicked") }
  end
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :cover_image, CoverImageUploader
  mount_uploader :profile_image, ProfileImageUploader

  validates :title, length: { maximum: 90 }
  validates :location_url, url: { allow_blank: true, schemes: %w[https http] }
  validate :end_time_after_start
  validates :slug, presence: { if: :published? }, format: /\A[0-9a-z-]*\z/
  before_validation :evaluate_markdown
  before_validation :create_slug
  after_save :bust_cache

  scope :in_the_future_and_published, lambda {
    where("starts_at > ?", Time.current)
      .where(published: true)
  }

  scope :in_the_past_and_published, lambda {
    where("starts_at < ?", Time.current)
      .where(published: true)
  }

  private

  def evaluate_markdown
    self.description_html = MarkdownProcessor::Parser.new(description_markdown).evaluate_markdown
  end

  def end_time_after_start
    if ends_at.nil? || starts_at.nil?
      errors.add(:starts_at, "and ends_at must not be nil")
    elsif ends_at < starts_at
      errors.add(:ends_at, "must be after start date")
    end
  end

  def create_slug
    self.slug = title_to_slug if slug.blank? && title.present? && published
  end

  def title_to_slug
    downcase = "#{id}-#{category}-#{title}"
    "#{downcase.parameterize}-#{starts_at.strftime('%m-%d-%Y')}"
  end

  def bust_cache
    Events::BustCacheWorker.perform_async
  end
end

app/models/webhook/event.rb
module Webhook
  class Event
    EVENT_TYPES = %w[
      article_created
      article_updated
      article_destroyed
    ].freeze

    attr_reader :event_type, :payload, :timestamp, :event_id

    def initialize(event_type:, payload: {})
      raise InvalidEvent unless EVENT_TYPES.include?(event_type)

      @event_type = event_type
      @payload = payload

      now = Time.current
      @timestamp = now.rfc3339
      @event_id = Secrets::Generator.sortable(now)
    end

    def as_json(*_args)
      Webhook::EventSerializer.new(self).serializable_hash
    end
  end

  class InvalidEvent < StandardError; end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < ApplicationController
    layout "admin"
    include ApplicationHelper

    def index
      @events = Event.order(starts_at: :desc).page(params[:page]).per(20)
    end

    def new
      @event = Event.new(
        location_name: "#{URL.domain}/live",
        location_url: app_url,
        description_markdown: "*Description* *Pre-requisites:* *Bio*",
      )
    end

    def edit
      @event = Event.find(params[:id])
    end

    def create
      @event = Event.new(event_params)
      if @event.save
        flash[:success] = "Successfully created event: #{@event.title}"
        redirect_to admin_events_path
      else
        flash[:danger] = @event.errors.full_messages
        render :new
      end
    end

    def update
      @event = Event.find(params[:id])
      if @event.update(event_params)
        flash[:success] = "#{@event.title} was successfully updated"
        redirect_to admin_events_path
      else
        flash[:danger] = @event.errors.full_messages
        render :edit
      end
    end

    private

    def event_params
      allowed_params = %i[
        title category event_date starts_at ends_at
        location_name cover_image location_url description_markdown published
        host_name profile_image live_now
      ]
      params.require(:event).permit(allowed_params)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_cache_control_headers, only: [:index]
  # No authorization required for entirely public controller

  def index
    @events = Event.in_the_future_and_published.sort_by(&:starts_at)
    @past_events = Event.in_the_past_and_published.sort_by(&:starts_at)
    set_surrogate_key_header "events_index_page"
    @past_events.reverse!
  end

  def show
    @event = Event.find_by!(slug: params[:id])
  end
end

app/views/admin/events/_event_form.html.erb
<div class="crayons-card p-6">
  <%= form_for [:admin, @event] do |f| %>
    <div class="crayons-field">
      <%= f.label :cover_image, class: "crayons-field__label" %>
      <%= f.file_field :cover_image, class: "crayons-field" %>
    </div>
    <div class="crayons-field">
      <%= f.label :profile_image, class: "crayons-field__label" %> (for live notification):
      <%= f.file_field :profile_image, class: "crayons-field" %>
      <img src="<%= @event.profile_image_url %>" style="width: 25%;" alt="event profile image">
    </div>
    <div class="crayons-field">
      <%= f.label :title, class: "crayons-field__label" %>
      <%= f.text_field :title, maxlength: 90, size: 40, required: true, class: "crayons-textfield" %>
    </div>
    <div class="crayons-field">
      <%= f.label :host_name, class: "crayons-field__label" %>
      <%= f.text_field :host_name, size: 40, required: true, class: "crayons-textfield" %>
    </div>
    <div class="crayons-field">
      <%= f.label :category, class: "crayons-field__label" %>
      <%= f.select :category, ["AMA", "Workshop", "Talk", "Town Hall"], required: true, class: "crayons-select" %>
    </div>
    <div class="crayons-field">
      <%= f.label :starts_at, class: "crayons-field__label" %>
      <fieldset>
      <%= f.datetime_select :starts_at, required: true, include_blank: true, start_year: Time.current.year, end_year: Time.current.year + 2, class: "crayons-select" %> UTC Time Only (4 hours ahead of eastern time)
      </fieldset>
    </div>
    <div class="crayons-field">
      <%= f.label :ends_at, class: "crayons-field__label" %>
      <fieldset>
      <%= f.datetime_select :ends_at, required: true, include_blank: true, start_year: Time.current.year, end_year: Time.current.year + 2, class: "crayons-select" %> UTC Time Only (4 hours ahead of eastern time)
      </fieldset>
    </div>
    <div class="crayons-field">
      <%= f.label :location_name, class: "crayons-field__label" %>
      <%= f.text_field :location_name, required: true, class: "crayons-textfield" %>
    </div>
    <div class="crayons-field">
      <%= f.label :location_url, class: "crayons-field__label" %>
      <%= f.text_field :location_url, required: true, class: "crayons-textfield" %>
    </div>
    <div class="crayons-field">
      <%= f.label :description_markdown, class: "crayons-field__label" %>
      <%= f.text_area :description_markdown, size: "45x10", required: true, class: "crayons-textfield" %>
    </div>
    <div class="crayons-field">
      <%= f.label :published, class: "crayons-field__label" %>
      <%= f.check_box :published, class: "crayons-checkbox" %>
    </div>
    <div class="crayons-field">
      <%= f.label :live_now, class: "crayons-field__label" %>
      <%= f.check_box :live_now, class: "crayons-checkbox" %>
    </div>
    <%= f.submit class: "crayons-btn" %>
  <% end %>
</div>

app/views/admin/events/edit.html.erb
<div class="crayons-card p-6 mb-6">
  <h2 class="crayons-title mb-6">Edit Event: <%= @event.title.to_s %></h2>
    <%= render "event_form" %>
</div>

app/views/admin/events/index.html.erb
<header class="flex items-center mb-6">
  <h2 class="crayons-title">Events</h2>
  <%= link_to "New Event", new_admin_event_path, class: "ml-auto crayons-btn crayons-btn--s" %>
</header>
<br>

<div class="crayons-card p-6 pages__table">
  <h3>Upcoming Events</h3>
  <% @events.each do |event| %>
    <% if event.starts_at.future? %>
      <div class="flex py-2 items-center">
        <%= event.title %>
        <% if event.cover_image_url.present? %>
          <img class="mx-auto mt-3" width="40" height="40" src="<%= event.cover_image_url %>" alt="event cover image">
        <% end %>
        <%= link_to "Edit", edit_admin_event_path(event.id), class: "ml-auto crayons-btn crayons-btn--s crayons-btn--secondary" %>
      </div>
      <hr>
    <% end %>
  <% end %>
</div>
<br>

<div class="crayons-card p-6 pages__table">
<h3>Past Events</h3>
  <% @events.each do |event| %>
    <% if !event.starts_at.future? %>
      <div class="flex py-2 items-center">
        <%= event.title %>
        <% if event.cover_image_url.present? %>
          <img class="mx-auto mt-3 justify-content-center" width="40" height="40" src="<%= event.cover_image_url %>" alt="event cover image">
        <% end %>
        <%= link_to "Edit", edit_admin_event_path(event.id), class: "ml-auto crayons-btn crayons-btn--s crayons-btn--secondary" %>
      </div>
      <hr>
    <% end %>
  <% end %>
</div>

app/views/admin/events/new.html.erb
<div class="crayons-card p-6 mb-6">
  <h2 class="crayons-title mb-6">Create New Event</h2>
    <%= render "event_form" %>
</div>